version: 3.0.21.{build}
image: Visual Studio 2022
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- cmd: dotnet build  -c Release EFCore.Taos.sln
artifacts:
- path: src\IoTSharp.Data.Taos\bin\Release\IoTSharp.Data.Taos.*.nupkg
  name: IoTSharp.Data.Taos
- path: src\EFCore.Taos.Core\bin\Release\IoTSharp.EntityFrameworkCore.Taos.*.nupkg
  name: IoTSharp.EntityFrameworkCore.Taos
- path: src\IoTSharp.HealthChecks.Taos\bin\Release\*.nupkg
  name: IoTSharp.HealthChecks.Taos
- path: src\IoTSharp.ORM.Taos\bin\Release\*.nupkg
  name: IoTSharp.ORM.Taos

  
